version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: schoolsystem-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  grades-service:
    build:
      context: .
      dockerfile: SchoolSystem.Grades/Dockerfile
    container_name: schoolsystem-grades
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Data Source=/app/grades.db"
    volumes:
      - ./SchoolSystem.Grades/grades.db:/app/grades.db
    depends_on:
      - rabbitmq

